apiVersion: v1
kind: ServiceAccount
metadata:
  name: "s3-minio"
  namespace: kubeflow-user
secrets:
  - name: default-token-ct4f6
  - name: s3-minio-sc
---
apiVersion: v1
kind: Secret
metadata:
  name: "s3-minio-sc"
  namespace: kubeflow-user
  annotations:
    serving.kubeflow.org/s3-endpoint: "minio-service.kubeflow.svc.cluster.local:9000"
    serving.kubeflow.org/s3-verifyssl: "0" 
    serving.kubeflow.org/s3-usehttps: "0"
    serving.kubeflow.org/s3-region: "us-east-1"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bWluaW8K
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjMK
  # awsAccessKeyID: x
  # awsSecretAccessKey: x
  # AWS_ACCESS_KEY_ID: x
  # AWS_SECRET_ACCESS_KEY: x
  # AWS_ENDPOINT_URL: minio-s3-lati-service.minio-gateway.svc.cluster.local:9000
  # S3_USE_HTTPS: "false"