apiVersion: v1
kind: Secret
metadata:
  name: "s3-minio-sc"
  namespace: kubeflow-user
  annotations:
    serving.kubeflow.org/s3-endpoint: minio-service.kubeflow:9000 # replace with your s3 endpoint
    serving.kubeflow.org/s3-usehttps: "0" # by default 1, for testing with minio you need to set to 0
    # serving.kubeflow.org/s3-endpoint: minio-service.kubeflow.svc.cluster.local:9000
    # serving.kubeflow.org/s3-verifyssl: "0" 
    # serving.kubeflow.org/s3-usehttps: "0"
    # serving.kubeflow.org/s3-region: us-east-1
# type: Opaque
data:
  awsAccessKeyID: bWluaW8=
  awsSecretAccessKey: bWluaW8xMjM=

  # * this below is for kfserving > 0.4.0
  # * AWS_ACCESS_KEY_ID: bWluaW8K
  # * AWS_SECRET_ACCESS_KEY: bWluaW8xMjMK

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "s3-minio"
  namespace: kubeflow-user
secrets:
  - name: s3-minio-sc
