apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "toy"
  namespace: kubeflow-user
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "s3://serving/Toy/1/"
        serviceAccount: "s3-minio"
        minReplicas: 2
        maxReplicas: 3
        resources:
          requests:
            cpu: 1
            memory: 3Gi
          limits:
            cpu: 2
            memory: 4Gi