apiVersion: v1
kind: ServiceAccount
metadata:
  name: "s3-minio-lati"
  namespace: "kfservings"
secrets:
  - name: default-token-j6c8t
  - name: s3-minio-lati-sc
---
apiVersion: v1
kind: Secret
metadata:
  name: "s3-minio-lati-sc"
  namespace: kfservings
  annotations:
    serving.kubeflow.org/s3-endpoint: "minio-s3-lati-service.minio-gateway.svc.cluster.local:9000"
    serving.kubeflow.org/s3-verifyssl: "0" 
    serving.kubeflow.org/s3-usehttps: "0"
    serving.kubeflow.org/s3-region: "us-east-1"
type: Opaque
data:
  # awsAccessKeyID: x
  # awsSecretAccessKey: x
  # AWS_ACCESS_KEY_ID: x
  # AWS_SECRET_ACCESS_KEY: x
  AWS_ENDPOINT_URL: minio-s3-lati-service.minio-gateway.svc.cluster.local:9000
  S3_USE_HTTPS: "false"
  AWS_ACCESS_KEY_ID: x
  AWS_SECRET_ACCESS_KEY: x=

---
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "toy"
  namespace: "kfservings"
spec:
  default:
    predictor:
      tensorflow:
        storageUri: "s3://ASH-ADX01/yongxi/save/Toy/1"
        serviceAccount: "s3-minio-lati"
        minReplicas: 2
        maxReplicas: 3
        resources:
          requests:
            cpu: 1
            memory: 3Gi
          limits:
            cpu: 2
            memory: 4Gi