apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30010
      protocol: TCP
  selector:
    app: minio