apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: katib-worker
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 3
      restartPolicy: ExitCode
      template:
        spec:
          containers:
            - name: tensorflow
              image: katib.io/logistic:test
              args:
                - --opt=Adam
                - --lr=0.01
                - --hidden-units=3
              resources:
                request:
                  cpu: 1
                  memory: 2Gi
                limits:
                  cpu: 2
                  memory: 4Gi
          # affinity:
          #   podAntiAffinity:
          #     preferredDuringSchedulingIgnoredDuringExecution:
          #       - weight: 70
          #         podAffinityTerm:
          #           labelSelector:
          #             matchExpressions:
          #               - key: tf-job-name
          #                 operator: In
          #                 values:
          #                   - multi-worker
          #           topologyKey: kubernetes.io/hostname