apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-minio
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: pyspark:minio-test
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/work-dir/spark-test.py
  sparkVersion: "2.4.5"
  sparkConf:
    "spark.sql.shuffle.partitions": "200"
    "spark.driver.maxResultSize": "5g"
  hadoopConf:
    "fs.s3a.endpoint": "http://minio-service.minio-gateway.svc.cluster.local:9000"
    "fs.s3a.access.key": "<s3_access_key>"
    "fs.s3a.secret.key": "<s3_secret_key>"
    "fs.s3a.path.style.access": "true"
    "fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
  restartPolicy:
    type: Never
    # onFailureRetries: 3
    # onFailureRetryInterval: 10
    # onSubmissionFailureRetries: 5
    # onSubmissionFailureRetryInterval: 20
  driver:
    serviceAccount: sparkoperator-1594801785-spark
    cores: 1
    coreLimit: "4"
    memory: "8g"
    labels:
      version: 2.4.5
  executor:
    instances: 4
    cores: 1
    memory: "4g"
    labels:
      version: 2.4.5
