apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  selector:
    notebook-name: notebook
  clusterIP: None
  ports:
  - name: notebook
    port: 8888
    targetPort: 8888
  - name: comm
    port: 37371
    targetPort: 37371
  - name: blockmngr
    port: 6060
    targetPort: 6060
