apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-preprocess
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: pyspark:try
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/work-dir/first-try.py
  deps:
    jars: 
    - local:///opt/spark/jars/spark-tensorflow-connector_2.11-1.15.0.jar
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
    # onFailureRetries: 3
    # onFailureRetryInterval: 10
    # onSubmissionFailureRetries: 5
    # onSubmissionFailureRetryInterval: 20
  volumes:
  - hostPath:
      path: /home/sdev/s3mount/yongxi/training/test
      readOnly: false
    name: dataset
  driver:
    serviceAccount: sparkoperator-1594806612-spark
    cores: 1
    coreLimit: "2"
    memory: "512m"
    labels:
      version: 2.4.5
    volumeMounts:
    - mountPath: /test
      name: dataset
  executor:
    instances: 3
    cores: 1
    memory: "1g"
    labels:
      version: 2.4.5
    volumeMounts:
    - mountPath: /test
      name: dataset
